Repository vercel/commerce, pull requests merged in 2022-03, with the labels that each got.

#699 Bug: Visual Regressions
  site/components/product/ProductTag/ProductTag.module.css
Labels: bug

#626 Prevent click-outside from losing children refs
  site/components/common/UserNav/UserNav.tsx
  site/lib/click-outside/click-outside.tsx
Labels: checking

#691 Add lodash.debounce to Shopify provider package.json dependencies
  packages/commercejs/package.json
  packages/kibocommerce/package.json
  packages/ordercloud/package.json
  packages/saleor/package.json
  packages/shopify/package.json
  packages/spree/package.json
  packages/swell/package.json
Labels: awaiting response

#719 Bug Fix Round and Updates
  packages/kibocommerce/src/lib/immutability.ts
  packages/kibocommerce/src/lib/normalize.ts
  site/pages/[...pages].tsx
Labels: bug
